name: Sourcehawk Scan
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sourcehawk Scan
        uses: optum/sourcehawk-scan-github-action@main



